-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pixup
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pixup` ;

-- -----------------------------------------------------
-- Schema pixup
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pixup` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `pixup` ;

-- -----------------------------------------------------
-- Table `pixup`.`TBL_ESTADO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pixup`.`TBL_ESTADO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pixup`.`TBL_ESTADO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ESTADO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pixup`.`TBL_MUNICIPIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pixup`.`TBL_MUNICIPIO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pixup`.`TBL_MUNICIPIO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `MUNICIPIO` VARCHAR(45) NOT NULL,
  `TBL_ESTADO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_TBL_MUNICIPIO_TBL_ESTADO`
    FOREIGN KEY (`TBL_ESTADO_ID`)
    REFERENCES `pixup`.`TBL_ESTADO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_MUNICIPIO_TBL_ESTADO_idx` ON `pixup`.`TBL_MUNICIPIO` (`TBL_ESTADO_ID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pixup`.`TBL_COLONIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pixup`.`TBL_COLONIA` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pixup`.`TBL_COLONIA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `COLONIA` VARCHAR(45) NOT NULL,
  `CP` CHAR(5) NOT NULL,
  `TBL_MUNICIPIO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_TBL_COLONIA_TBL_MUNICIPIO1`
    FOREIGN KEY (`TBL_MUNICIPIO_ID`)
    REFERENCES `pixup`.`TBL_MUNICIPIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_COLONIA_TBL_MUNICIPIO1_idx` ON `pixup`.`TBL_COLONIA` (`TBL_MUNICIPIO_ID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pixup`.`TBL_USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pixup`.`TBL_USUARIO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pixup`.`TBL_USUARIO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NOT NULL,
  `PRIMER_APELLIDO` VARCHAR(45) NOT NULL,
  `SEGUNDO_APELLIDO` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
  `EMAIL` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pixup`.`TBL_DOMICILIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pixup`.`TBL_DOMICILIO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pixup`.`TBL_DOMICILIO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CALLE` VARCHAR(45) NOT NULL,
  `NUM_EXTERIOR` VARCHAR(45) NOT NULL,
  `NUM_INTERIOR` VARCHAR(45) NULL,
  `TBL_COLONIA_ID` INT NOT NULL,
  `TBL_USUARIO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_TBL_DOMICILIO_TBL_COLONIA1`
    FOREIGN KEY (`TBL_COLONIA_ID`)
    REFERENCES `pixup`.`TBL_COLONIA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_DOMICILIO_TBL_USUARIO1`
    FOREIGN KEY (`TBL_USUARIO_ID`)
    REFERENCES `pixup`.`TBL_USUARIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_DOMICILIO_TBL_COLONIA1_idx` ON `pixup`.`TBL_DOMICILIO` (`TBL_COLONIA_ID` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_DOMICILIO_TBL_USUARIO1_idx` ON `pixup`.`TBL_DOMICILIO` (`TBL_USUARIO_ID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pixup`.`TBL_ARTISTA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pixup`.`TBL_ARTISTA` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pixup`.`TBL_ARTISTA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pixup`.`TBL_DISQUERA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pixup`.`TBL_DISQUERA` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pixup`.`TBL_DISQUERA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pixup`.`TBL_DISCO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pixup`.`TBL_DISCO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pixup`.`TBL_DISCO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TITULO` VARCHAR(200) NOT NULL,
  `PRECIO` FLOAT NOT NULL,
  `EXISTENCIA` INT NOT NULL,
  `DESCUENTO` FLOAT NOT NULL,
  `FECHA_LANZAMIENTO` DATE NOT NULL,
  `IMAGEN` VARCHAR(120) NOT NULL,
  `TBL_ARTISTA_ID` INT NOT NULL,
  `TBL_DISQUERA_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_TBL_DISCO_TBL_ARTISTA1`
    FOREIGN KEY (`TBL_ARTISTA_ID`)
    REFERENCES `pixup`.`TBL_ARTISTA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_DISCO_TBL_DISQUERA1`
    FOREIGN KEY (`TBL_DISQUERA_ID`)
    REFERENCES `pixup`.`TBL_DISQUERA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_DISCO_TBL_ARTISTA1_idx` ON `pixup`.`TBL_DISCO` (`TBL_ARTISTA_ID` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_DISCO_TBL_DISQUERA1_idx` ON `pixup`.`TBL_DISCO` (`TBL_DISQUERA_ID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pixup`.`TBL_ORDEN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pixup`.`TBL_ORDEN` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pixup`.`TBL_ORDEN` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `COSTO_TOTAL` FLOAT NOT NULL,
  `FECHA` TIMESTAMP NOT NULL,
  `CANTIDAD_TOTAL` INT NOT NULL,
  `ESTATUS_ENVIO` TINYINT NOT NULL,
  `COSTO_MAX` FLOAT NOT NULL,
  `TBL_USUARIO_ID` INT NOT NULL,
  `TBL_DISCO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `TBL_DISCO_ID`),
  CONSTRAINT `fk_TBL_ORDEN_TBL_USUARIO1`
    FOREIGN KEY (`TBL_USUARIO_ID`)
    REFERENCES `pixup`.`TBL_USUARIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_ORDEN_TBL_DISCO1`
    FOREIGN KEY (`TBL_DISCO_ID`)
    REFERENCES `pixup`.`TBL_DISCO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_ORDEN_TBL_USUARIO1_idx` ON `pixup`.`TBL_ORDEN` (`TBL_USUARIO_ID` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_ORDEN_TBL_DISCO1_idx` ON `pixup`.`TBL_ORDEN` (`TBL_DISCO_ID` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
